INSERT INTO PRODUCT(CODE, NAME, DESCRIPTION) VALUES ('webpage', 'Web Page', 'Web page for customer');
INSERT INTO PRODUCT(CODE, NAME, DESCRIPTION) VALUES ('graphics', 'Graphics', 'Designing graphics');
INSERT INTO PRODUCT(CODE, NAME, DESCRIPTION) VALUES ('seo', 'SEO', 'Managing SEO for customer');

INSERT INTO PRODUCT_SUBSCRIPTION(CUSTOMER_ID, PRODUCT_CODE) VALUES (1, 'webpage');
INSERT INTO PRODUCT_SUBSCRIPTION(CUSTOMER_ID, PRODUCT_CODE) VALUES (1, 'seo');
INSERT INTO PRODUCT_SUBSCRIPTION(CUSTOMER_ID, PRODUCT_CODE) VALUES (2, 'graphics');